name: Publish

on:
    release:
        types: [published]

jobs:
    release:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: 'yarn'
                  registry-url: 'https://registry.npmjs.org/'
                  package-manager-cache: false

            - run: yarn install --immutable

            - run: npm pkg set version=${GITHUB_REF_NAME}

            - run: yarn build

            - run: yarn npm publish --access public
